#!/usr/bin/env bash
#sh client configuration

Host *
   PasswordAuthentication no
   IdentityFile ~/.ssh/school
   SendEnv LANG LC_*
   HashknownHosts yes
   GSSAPIAuthentication yes
   GSSAPIDelegateCredentials no
